### ISSUE TITLE
Provide Support for Video Maps

### ISSUE THREAD

**Issue by Stonedtroll** [Unarekin/FoundryVTT-Battle-Transitions#14]
webm, mv4, etc. Currently, the screen is just black when using Battle Transitions.

**Comment by Unarekin** [comment]
Having some trouble reproducing the issue on my end.
I assume you're using a video as the background for a scene, or am I mistaken?

And to make sure it isn't something to do with one of the actual transition effects, rather than directly because of the video, if you could open the browser's debug console by pressing either F12 or CTRL+SHIFT+I, you should be able to find a line in there similar to:
```
⚔️ Battle Transitions | Transition end: [{...}]
```
right after a transition is run.

If you could right click on the bracketed section, the context menu should give you the option to `Copy object`.  If you'd paste that into a comment, it would help a great deal.

![image](https://github.com/user-attachments/assets/3a03492c-c8ae-4235-a513-ac88bd24ab83)

**Comment by Stonedtroll** [comment]
This is embarrassing. I went to get the information you requested, but I'm unable to reproduce the issue. It was happening consistently before. My apologies for the inconvenience.

**Comment by Unarekin** [comment]
No worries!
